// Databricks notebook source
// MAGIC %md ### Notebook Discovery
// MAGIC Elsevier Data Wranglers and Data Scientists have been using Databricks for over 6 years.  During that time, we have created thousands of notebooks.  For years, we have tried to search for notebooks within our workspace but this has proven difficult due to the current limited Databricks search functionality.  For example, wouldn't it be great if you could restrict searches to a specific user's workspace folder, a notebook name, a specific command language, the command text for a specific cell, or a command submitted date range?   Wouldn't it be great if you could discover notebooks that have been cloned from an original notebook but where these cloned notebooks have been slightly modified?  We have seen similar feedback posted to the Databricks forums over the past couple of years (below are some representative examples).
// MAGIC 
// MAGIC - I'm updating a source table and need to find all the notebooks that have that table. I tried using the search function in databricks UI, but my problem is I'm getting results from every folder, including other users. Is there a way to conditionally limit to a certain folder?
// MAGIC - How can I search across multiple workspaces? I want to search about 10 different ones, and searching each one manually would be time-consuming.
// MAGIC - Can you search notebooks using conditionals such as exact phrase, contains(not), wildcards, or regular expressions?
// MAGIC - Is there possibility to check all notebooks from one particular Databricks workspace and get an inventory of where notebooks are directly accessing data through ADLS locations rather than through the metastore.
// MAGIC - Is there a way to search a text in all notebooks?  I like to find out whether a delta table is used in any notebooks.
// MAGIC 
// MAGIC To address these limitations and more, Elsevier Labs has open sourced Notebook Discovery.  
// MAGIC 
// MAGIC This is a 100% notebook solution making it easy to integrate this functionality into your current Databricks environment regardless of whether your language of preference is Scala, Python, SQL, or R.  Some users may find it useful to run this tool over their own user folder.  Groups may find it useful to run this tool over all of the user folders for the members of their group.  We particularly found this useful for our Labs group.  Since the tool is scalable, organizations may find it useful to run this tool for all of the user folders in their organization.  Whatever your decision, we hope you find the tool useful.
// MAGIC 
// MAGIC Darin McBeath<br/>
// MAGIC Elsevier Labs
// MAGIC 
// MAGIC ##### Solution
// MAGIC Notebook Discovery consists of 3  notebooks.
// MAGIC 
// MAGIC - <i>NotebookIndex</i>
// MAGIC   - Creates the Notebook Discovery Index parquet file for all of the notebook information needed to power NotebookSearch and NotebookSimilarity. Each command in a notebook will be contained as a separate record in the index providing the capability to search at the command level (and not just the overall notebook).  For a more detailed description of the index structure that is generated, view the <a href="$./NotebookIndex">NotebookIndex</a> notebook documentation. 
// MAGIC   
// MAGIC - <i>NotebookSimilarity</i>
// MAGIC   - Compares the notebooks in the Notebook Discovery Index parquet file generated by NotebookIndex to produce a similarity score for every notebook.  We use the [MinHash](https://spark.apache.org/docs/latest/ml-features.html#minhash-for-jaccard-distance) for Jaccard distance algorithm to allow for scalability to tens of thousands of notebooks.  For more detailed information, view the <a href="$./NotebookSimilarity">NotebookSimilarity</a> notebook documentation.
// MAGIC   
// MAGIC - <i>NotebookSearch</i>
// MAGIC   - Provides examples for searching the Notebook Discovery Index parquet file generated by NotebookIndex.  Included is a UDF to format the search results into HTML so the links to the notebook (or the specific command) can be quickly and easily followed.  For more detailed information, view the <a href="$./NotebookSearch">NotebookSearch</a> notebook for more information.
// MAGIC   
// MAGIC 
// MAGIC ##### Download
// MAGIC 
// MAGIC Notebook Discovery is provided as a [download](https://github.com/elsevierlabs-os/NotebookDiscovery/tree/main/download/NotebookDiscovery-1.0.0.dbc).  This is a DBC (Databricks archive) file.
// MAGIC 
// MAGIC 
// MAGIC ##### Installation
// MAGIC 
// MAGIC From the Databricks UI, simply import the Notebook Discovery archive downloaded above into the workspace folder where you want to place Notebook Discovery. The workspace folder where the archive is imported is unrelated to the workspace folders that you want to index.
// MAGIC 
// MAGIC ##### Execution
// MAGIC 
// MAGIC In addition to the 3 notebooks discussed above, there are also a couple of run notebooks that have been created to simplify using Notebook Discovery.  Using the run notebooks, you can simply adjust the parameters required of the notebook and run the notebook.  While the run notebooks are implemented in scala, they are straightforward and should be usable by users familiar with other programming languages.  
// MAGIC 
// MAGIC - NotebookIndexRun
// MAGIC   - The first run notebook to execute is <a href="$./NotebookIndexRun">NotebookIndexRun</a> to generate the Notebook Discovery Index parquet file which the subsequent notebooks require.  After NotebookIndexRun completes successfully, you can run either  NotebookSimilarityRun or model queries contained in NotebookSearch.
// MAGIC   - Arguments include the following:
// MAGIC     - path. The location of the notebook to run (in this case NotebookIndex).  It is assumed this notebook is in the same folder as it's run notebook.
// MAGIC     - timeoutSeconds.  Number of seconds to allow for the notebook execution (currently set at 2 hours).
// MAGIC     - folders.  Comma separated list of workspace folders to crawl when generating the Notebook Discovery Index.
// MAGIC     - indexFilename. Where to place the generated  Notebook Discovery Index parquet file.  Typically an area mounted on Databricks.
// MAGIC     - overwrite. Whether the Notebook Discovery Index parquet file should be overwritten if it already exists.  'False' will not overwrite.  'True' will overwrite.
// MAGIC     - parallelization. The number of concurrent requests that will be sent to Databricks through the REST APIs when creating the index (currently set at 8).
// MAGIC   - Below is a sample request.
// MAGIC ```
// MAGIC dbutils.notebook.run(path="NotebookIndex",
// MAGIC                               timeoutSeconds=7200,
// MAGIC                               arguments=Map("folders" -> """
// MAGIC                                                             /Users/someone1@elsevier.com/,
// MAGIC                                                             /Users/someone2@elsevier.com/
// MAGIC                                                             """,
// MAGIC                                             "indexFilename" -> "/mnt/some-mount-point/DatabricksNotebookSearch/index",
// MAGIC                                             "overwrite" -> "False",
// MAGIC                                             "parallelization" -> "8"))                                            
// MAGIC ```
// MAGIC 
// MAGIC - NotebookSimilarityRun
// MAGIC   - If you desire to generate similarity scores for the notebooks, execute <a href="$./NotebookSimilarityRun">NotebookSimilarityRun</a> to generate the Notebook Discovery Similarity file.  After NotebookSimilarityRun completes successfully, you can analyze the resulting parquet file and explore similar notebooks.
// MAGIC   - Arguments include the following:
// MAGIC     - path. The location of the notebook to run (in this case NotebookSimilarity).  It is assumed this notebook is in the same folder as it's run notebook.
// MAGIC     - timeoutSeconds.  Number of seconds to allow for the notebook execution (currently set at 2 hours)
// MAGIC     - indexFilename. Location of the Notebook Discovery Index parquet file generated by NotebookIndex.
// MAGIC     - similarityFilename. Where to place the generated  Notebook Discovery Similarity parquet file  Typically an area mounted on Databricks.
// MAGIC     - overwrite. Whether the Notebook Discovery Similarity parquet file should be overwritten if it already exists.  'False' will not overwrite.  'True' will overwrite.
// MAGIC     - similarDistance. Max Jaccard distance to use when comparing notebooks
// MAGIC     - vocabSize. Number of unique words (ngrams) you would expect to occur across all of the notebooks that were indexed.
// MAGIC     - ngramSize. Size of the ngram to use when tokenizing and comparing notebooks
// MAGIC     - minDocFreq. Number of notebooks an ngram must occur before it is included in the vocabulary
// MAGIC   - Below is a sample request.
// MAGIC ```
// MAGIC dbutils.notebook.run(path="NotebookSimilarity",
// MAGIC                               timeoutSeconds=7200,
// MAGIC                               arguments=Map("indexFilename" -> "/mnt/some-mount-point/DatabricksNotebookSearch/index", 
// MAGIC                                             "similarityFilename" -> "/mnt/some-mount-point/DatabricksNotebookSearch/ndex-similarity",
// MAGIC                                             "overwrite" -> "False",
// MAGIC                                             "similarDistance" -> ".25",
// MAGIC                                             "vocabSize" -> "5000000",
// MAGIC                                             "ngramSize" -> "5",
// MAGIC                                             "minDocFreq" -> "1"))                                            
// MAGIC ```
// MAGIC   
// MAGIC - NotebookSearch
// MAGIC   - If you desire to find notebooks or commands that contain specific text, then look at <a href="$./NotebookSearch">NotebookSearch</a> for examples.  Since the Notebook Discovery Index is a parquet file, basic filter and contains operations can be used to identify notebooks and commands satisfying your query criteria.   
// MAGIC   - Below is a simple example that searches notebooks where the language is 'scala', the folder starts with  '/Users/d.mcbeath@elsevier.com/' and the command text contains 'udf' and displays 10 results.
// MAGIC ```
// MAGIC   val notebookCommands = spark.read.parquet(indexFilename)
// MAGIC   displaySearchResults(notebookCommands.filter($"cLang" === "scala")
// MAGIC                                        .filter($"cText".contains("udf"))
// MAGIC                                        .filter($"nbFolder".startsWith("/Users/d.mcbeath@elsevier.com/")),num=10)                                       
// MAGIC ```
// MAGIC 
// MAGIC ##### Assumptions
// MAGIC - Notebook Discovery Index and Similarity files are currently written as a parquet files.  If a desire is to use Databricks tables, then one could easily add another step to the Run jobs to create a table from the parquet files or adjust the underlying code to write tables instead of a parquet files.
// MAGIC 
// MAGIC ##### Limitations
// MAGIC - If a notebook name contains a "/" character, this notebook will currently be ignored.
// MAGIC - If an exported notebook contents exceeds (10 MB), the notebook will not be processed.
// MAGIC - The Notebook Discovery Index parquet file is a static point in time snapshot.  If your notebooks are updated regularly, then you may want to rerun the NotebookIndexRun on a regular basis (such as weekly).
// MAGIC - The notebooks to be indexed by Notebook Discovery must be stored in the Databricks workspace and not an external repository such as github.
// MAGIC - The notebooks to be indexed by Notebook Discovery must have read permissions for the user that runs NotebookIndexRun.
// MAGIC - In order to view the notebooks (and commands) linked from NotebookSearch, users will need to have read permissions for those notebooks.
// MAGIC 
// MAGIC ##### Future Plans
// MAGIC - We plan to record the user/group permissions for each notebook in the Notebook Discovery Index parquet file.  This would allow filtering on the permissions associated with a notebook.  This information could also be used to filter the NotebookSearch results to only those that are accessible by a user.
// MAGIC - Improve parallelization.  Currently, if only one folder is specified in the folders argument for NotebookIndexRun, there is no parallelization.
// MAGIC 
// MAGIC ##### License
// MAGIC 
// MAGIC MIT License
// MAGIC 
// MAGIC Copyright (c) 2021 Elsevier 
// MAGIC 
// MAGIC Permission is hereby granted, free of charge, to any person obtaining a copy
// MAGIC of this software and associated documentation files (the "Software"), to deal
// MAGIC in the Software without restriction, including without limitation the rights
// MAGIC to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// MAGIC copies of the Software, and to permit persons to whom the Software is
// MAGIC furnished to do so, subject to the following conditions:
// MAGIC 
// MAGIC The above copyright notice and this permission notice shall be included in all
// MAGIC copies or substantial portions of the Software.
// MAGIC 
// MAGIC THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// MAGIC IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// MAGIC FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// MAGIC AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// MAGIC LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// MAGIC OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// MAGIC SOFTWARE.`
